# numpy100题练习

运行 `initialize.py`文件，采用`hint(n)` 和 `answer(n)`命令（n是题目号），方便查询问题的解答。

In [1]:
%run initialise.py

## 导入numpy包并命名为`np` (★☆☆)

In [2]:
import numpy as np
np.random.seed(2020)

## 打印numpy的版本和配置 (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


## 创建一个长度为10的空向量(null vector) (★☆☆)

In [4]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 怎样去查看一个数组的内存大小?(★☆☆)

In [5]:
v = np.zeros([10, 10])
print("该数组的内存大小为%d bytes" % (v.size * v.itemsize))

该数组的内存大小为800 bytes


## 怎样从命令行中获得numpy的add函数? (★☆☆)

In [6]:
# %run python -c "import numpy; numpy.info(numpy.add)"
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

## 创建一个长度为10的除了第五位为1其他全为0的向量 (★☆☆)

In [7]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 创建一个值从10到49的向量 (★☆☆)

In [8]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 反转一个向量(使第一个元素位于最后) (★☆☆)

In [9]:
v = np.arange(10, 50)
v = v[::-1]
print(v)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## 创建一个3x3的矩阵，值从0到8 (★☆☆)

In [10]:
m = np.arange(0, 9).reshape((3, 3))
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 从向量[1,2,0,0,4,0]找到非0元素的index(★☆☆)

In [11]:
indeces = np.nonzero([1, 2, 0, 0, 4, 0])
print(indeces)

(array([0, 1, 4], dtype=int64),)


## 创建一个3x3的单位矩阵 (★☆☆)

In [12]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 创建一个3x3x3的随机矩阵 (★☆☆)

In [13]:
v = np.random.random((3, 3 ,3))
v

array([[[0.98627683, 0.87339195, 0.50974552],
        [0.27183571, 0.33691873, 0.21695427],
        [0.27647714, 0.34331559, 0.86215894]],

       [[0.15669967, 0.14088724, 0.75708028],
        [0.73632492, 0.35566309, 0.34109302],
        [0.66680305, 0.21710064, 0.56142698]],

       [[0.12417878, 0.31973648, 0.95321387],
        [0.13735679, 0.5694131 , 0.97566548],
        [0.50336706, 0.66766421, 0.0341915 ]]])

## 创建一个10x10的随机矩阵，找到其中的最大值和最小值 (★☆☆)

In [14]:
v = np.random.random((10, 10))
v_max, v_min = v.max(), v.min()
print("矩阵的最大值是", v_max)
print("矩阵的最小值是", v_min)

矩阵的最大值是 0.994458699682387
矩阵的最小值是 0.01402672984617559


## 创建一个大小为30的随机向量，并找到平均值(★☆☆)

In [15]:
v = np.random.random(30)
mean = v.mean()
print("向量的平均值是", mean)

向量的平均值是 0.4676903094488819


## 创建一个二维数组，其边框均为1，内部均为0 (★☆☆)

In [16]:
v = np.ones((5, 5))
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 如何在现有数组周围添加边框（用0填充）？ (★☆☆)

In [17]:
answer(16)
v = np.ones((5, 5))
v = np.pad(v, pad_width=1, mode='constant', constant_values= 0)
print(v)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## 下列表达式的输出值是什么？ (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


## 创建一个5x5矩阵，值为1,2,3,4的元素刚好在对角线下方 (★☆☆)

In [19]:
v = np.diag(1+np.arange(4), k=-1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 创建一个8x8矩阵，并将其填充为一个棋盘图案 (★☆☆)

In [20]:
v = np.zeros((8, 8), dtype=int)
v[1::2, ::2] = 1
v[::2, 1::2] = 1
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 一个(6,7,8)的数组，第100个元素的索引(x,y,z)是什么？(★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


## 使用tile函数创建8x8棋盘矩阵 (★☆☆)

In [22]:
v = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 将5x5随机矩阵标准化(★☆☆)

In [23]:
v = np.random.random((5, 5))
v = (v - v.mean()) / (v.std())
print(v)

[[ 1.21860948 -1.38683116  0.93486875  0.79671189 -0.12975486]
 [-1.51118982  0.64691737 -0.99910049  1.58294403  0.25398664]
 [ 1.19400763 -0.50308009 -0.9650361   0.09036114  1.74470005]
 [ 1.35922165 -1.34826342  0.04632723  0.40221478 -1.25828359]
 [-0.30919506  0.39787125 -0.08660753 -0.85994307 -1.31145672]]


## 创建将颜色描述为四个无符号字节（RGBA）的自定义dtype (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte, (1,)),
                  ("g", np.ubyte, (1,)),
                  ("b", np.ubyte, (1,)),
                  ("a", np.ubyte, (1,))])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

## 将5x3矩阵乘以3x2矩阵（实矩阵乘积）(★☆☆)

In [25]:
z = np.ones((5, 3)) @ np.ones((3, 2))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 给定一个1维数组，在3和8之间的所有元素取反 (★☆☆)

In [26]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## 以下代码的输出是什么? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5), -1))
print(np.sum(range(5), -1))

9
10


## 给定一个整数向量Z，下面那些表达式是合法的? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.arange(1, 6)
try:
    print(Z)
    print(Z ** Z)
    print(2 << Z >> 2)
    print(Z < -Z)
    print(1j * Z)
    print(Z/1/1)
    print(Z<Z>Z)
except Exception as e:
    print(e)

[1 2 3 4 5]
[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


## 下列表达式的运行结果是什么?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print("浮点除法（由于除以0，结果为nan）：", np.array(0) / np.array(0))
print("整数除法（由于除以0，结果为0）：", np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

浮点除法（由于除以0，结果为nan）： nan
整数除法（由于除以0，结果为0）： 0
[-2.14748365e+09]


D:\MyPythonWork\data-analysis\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\MyPythonWork\data-analysis\venv\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 如何四舍五入一个浮点数组? (★☆☆)

In [30]:
Z = np.random.uniform(-10,+10,10)
print("原始数组：", Z)
print("四舍五入之后的数组：", np.copysign(np.round(np.abs(Z)), Z))

原始数组： [ 9.69644433 -9.86869135 -9.14011455  5.00163776  4.79248361  9.98089975
  2.09177585 -6.85975869 -8.23288133  7.05125846]
四舍五入之后的数组： [ 10. -10.  -9.   5.   5.  10.   2.  -7.  -8.   7.]


## 如何找出两个数组的公共元素？ (★☆☆)

In [31]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print("Z1 =", Z1)
print("Z2 =", Z2)
print("公共元素：", np.intersect1d(Z1, Z2))

Z1 = [1 6 3 4 3 1 1 1 1 5]
Z2 = [0 6 5 8 9 4 8 0 7 9]
公共元素： [4 5 6]


## 如何忽略所有numpy的警告（warning）信息（不推荐）? (★☆☆)

In [32]:
# 设置ignore模式
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
# 再重新设置为默认模式
_ = np.seterr(**defaults)

In [33]:
# 一个等价的方式，用一个上下文管理器（context manager）：
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

## 下列表达式是为True吗?  (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


D:\MyPythonWork\data-analysis\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


## 如何获得昨天，今天和明天的日期？ (★☆☆)

In [35]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("昨天：", yesterday)
print("今天：", today)
print("明天：", tomorrow)

昨天： 2020-03-08
今天： 2020-03-09
明天： 2020-03-10


## 如何获得2016年7月的所有日期 (★★☆)

In [36]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


## 如何计算`((A+B)*(-A/2))`（不用其他临时变量）？ (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
print((A + B) * (-A / 2))

[-1.5 -1.5 -1.5]


## 使用5种不同的方法得到随机数组的整数部分 (★★☆)

In [38]:
Z = np.random.uniform(0, 10, 10)
print("原始数组：", Z)

print(np.floor(Z))
print(np.ceil(Z) - 1)
print(Z.astype(int))
print(Z - Z % 1)
print(np.trunc(Z))
print(np.fix(Z))

原始数组： [9.35124073 5.86274897 2.29322815 7.28914076 7.09990838 1.57192708
 7.09753722 6.5276162  4.68139041 6.96824207]
[9. 5. 2. 7. 7. 1. 7. 6. 4. 6.]
[9. 5. 2. 7. 7. 1. 7. 6. 4. 6.]
[9 5 2 7 7 1 7 6 4 6]
[9. 5. 2. 7. 7. 1. 7. 6. 4. 6.]
[9. 5. 2. 7. 7. 1. 7. 6. 4. 6.]
[9. 5. 2. 7. 7. 1. 7. 6. 4. 6.]


## 创建一个5x5矩阵，每一行的值范围为从0到4 (★★☆)

In [39]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 用一个可生成10个整数的生成函数，构建一个数组(★☆☆)

In [40]:
def generate():
    for x in range(0, 20, 2):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


## 创建一个大小为10的向量，其值范围从0到1，但都不包括0和1 (★★☆)

In [41]:
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 创建一个大小为10的随机向量并对其排序 (★★☆)

In [42]:
Z = np.random.random(10)
print("原始数组：", Z)
Z.sort()
print("排序后的数组：", Z)

原始数组： [0.41716292 0.21167967 0.26998065 0.45911123 0.62444253 0.86925274
 0.80863208 0.86694944 0.56207492 0.54753291]
排序后的数组： [0.21167967 0.26998065 0.41716292 0.45911123 0.54753291 0.56207492
 0.62444253 0.80863208 0.86694944 0.86925274]


## 如何对一个小数组求和，比使用np.sum更快? (★★☆)

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

## 给定两个随机数组A和B，检查它们是否相等 (★★☆)

In [44]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# 假设array的维度(shape)相同和一个误差容限（tolerance）
# numpy的allclose方法，比较两个array是不是每一元素都相等，默认在1e-05的误差范围内
equal = np.allclose(A,B)
print("np.allclose(A,B)=", equal)

# 检查维度和元素值，没有误差容限（值必须完全相等）
equal = np.array_equal(A,B)
print("np.array_equal(A,B)=", equal)

np.allclose(A,B)= False
np.array_equal(A,B)= False


## 使数组不可变（只读）(★★☆)

In [45]:
Z = np.zeros(10)
Z.flags.writeable = False
try:
    Z[0] = 1
except Exception as e:
    print(e)

assignment destination is read-only


## 给定一个笛卡尔坐标下的10x2随机矩阵，将它们转换为极坐标 (★★☆)

直角坐标转换为极坐标：$$\left\{\begin{array}{l} 
\rho^2 = x^2+y^2 \\
\tan \theta = y / x
\end{array} \right.$$

In [46]:
Z = np.random.random((10, 2))
X, Y = Z[:,0], Z[:,1]
roh = np.sqrt(X **2 + Y ** 2)
theta = np.arctan2(Y, X)
print(roh)
print(theta)

[0.7936571  0.91515051 0.54513121 0.52785283 0.60512269 1.2144844
 0.31751993 1.15312958 1.05454233 0.82870749]
[0.84871636 0.40288706 0.5689557  0.24474744 1.24136968 0.76648131
 1.35557698 0.88802125 0.68992251 0.83443572]


## 创建大小为10的随机向量，将最大值替换为0 (★★☆)

In [47]:
Z = np.random.random(10)
print("原始数组：", Z)
Z[Z.argmax()] = 0
print("替换后的数组：", Z)

原始数组： [0.73036702 0.09577231 0.38198055 0.44024819 0.63547853 0.18855637
 0.72641305 0.09640746 0.83393953 0.7756333 ]
替换后的数组： [0.73036702 0.09577231 0.38198055 0.44024819 0.63547853 0.18855637
 0.72641305 0.09640746 0.         0.7756333 ]


## 创建一个元素为(x, y)数组，其中x和y的值都是从[0, 1]范围内 (★★☆)

In [48]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 给定X和Y两个数组，构造柯西（Cauchy）矩阵C (Cij =1/(xi - yj)) (★★☆)

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
# 打印矩阵C的行列式
print(np.linalg.det(C))

3638.163637117973


## 打印每个numpy基础类型的最小和最大的可表示值 (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print("%s 类型的最小值：%s" % (dtype.__name__, np.iinfo(dtype).min))
    print("%s 类型的最大值：%s" % (dtype.__name__, np.iinfo(dtype).max))
for dtype in [np.float32, np.float64]:
    print("%s 类型的最小值：%s" % (dtype.__name__, np.finfo(dtype).min))
    print("%s 类型的最小值：%s" % (dtype.__name__, np.finfo(dtype).max))
    print("%s 类型的非负最小值：%s" % (dtype.__name__, np.finfo(dtype).eps))

int8 类型的最小值：-128
int8 类型的最大值：127
int32 类型的最小值：-2147483648
int32 类型的最大值：2147483647
int64 类型的最小值：-9223372036854775808
int64 类型的最大值：9223372036854775807
float32 类型的最小值：-3.4028235e+38
float32 类型的最小值：3.4028235e+38
float32 类型的非负最小值：1.1920929e-07
float64 类型的最小值：-1.7976931348623157e+308
float64 类型的最小值：1.7976931348623157e+308
float64 类型的非负最小值：2.220446049250313e-16


## 如何打印数组所有的值？ (★★☆)

In [51]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## 如何在向量中找到一个最接近的值（给定一个标量值）？(★★☆)

In [52]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
print("给定的标量值：", v)
index = (np.abs(Z-v)).argmin()
print(Z[index])

给定的标量值： 21.469934526843616
21


## 创建表示位置(x,y)和颜色(r,g,b)的结构化数组 (★★☆)

In [53]:
position = np.dtype([("x", float, (1,)),
                    ("y", float, (1,))])
color = np.dtype([("r", float, (1,)),
                  ("g", float, (1,)),
                  ("b", float, (1,)),])
Z = np.zeros(10, [('position', position), ('color', color)])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


## 用维度为(100,2)的随机向量表示的坐标系，计算点与点的距离  (★★☆)

In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.17220447 1.03484016 1.03211668 0.91958728 0.88619355
  0.51717434 0.98375286 0.44606899 0.64709028]
 [0.17220447 0.         0.98860521 0.99211302 0.83100653 0.91717841
  0.38828216 0.85487705 0.28553546 0.68262633]
 [1.03484016 0.98860521 0.         0.03781548 0.28654275 0.44273569
  0.67962351 0.55302773 0.84523543 0.52287966]
 [1.03211668 0.99211302 0.03781548 0.         0.31777667 0.40925092
  0.69390822 0.58722019 0.85875618 0.50137234]
 [0.91958728 0.83100653 0.28654275 0.31777667 0.         0.62739232
  0.46574158 0.27586848 0.62789371 0.59621963]
 [0.88619355 0.91717841 0.44273569 0.40925092 0.62739232 0.
  0.77268581 0.89387429 0.90673674 0.2391616 ]
 [0.51717434 0.38828216 0.67962351 0.69390822 0.46574158 0.77268581
  0.         0.46844846 0.16610682 0.59106466]
 [0.98375286 0.85487705 0.55302773 0.58722019 0.27586848 0.89387429
  0.46844846 0.         0.59099974 0.82607909]
 [0.44606899 0.28553546 0.84523543 0.85875618 0.62789371 0.90673674
  0.16610682 0.59099

In [55]:
# 使用scipy更快
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.18411221 0.2042003  0.17135026 0.37226371 0.0893311
  0.61333672 0.28044801 0.31779409 0.54535927]
 [0.18411221 0.         0.02493209 0.30616883 0.51201454 0.15910031
  0.48185924 0.31318673 0.46001603 0.38428423]
 [0.2042003  0.02493209 0.         0.33080306 0.53684869 0.18373397
  0.48259389 0.30939295 0.48476578 0.37800539]
 [0.17135026 0.30616883 0.33080306 0.         0.20770699 0.1470738
  0.6100322  0.44478716 0.15446034 0.58577136]
 [0.37226371 0.51201454 0.53684869 0.20770699 0.         0.35357525
  0.73301396 0.62667361 0.05447342 0.74475825]
 [0.0893311  0.15910031 0.18373397 0.1470738  0.35357525 0.
  0.53138473 0.35490792 0.30113304 0.47588318]
 [0.61333672 0.48185924 0.48259389 0.6100322  0.73301396 0.53138473
  0.         0.79167257 0.70508908 0.15797433]
 [0.28044801 0.31318673 0.30939295 0.44478716 0.62667361 0.35490792
  0.79167257 0.         0.57382438 0.67782701]
 [0.31779409 0.46001603 0.48476578 0.15446034 0.05447342 0.30113304
  0.70508908 0.5738243

## 如何将float（32位）数组转换为整数（32位）？

In [56]:
Z = (np.random.rand(10)*100).astype(np.float32)
print("原始数组：", Z)

# 第1种方法
print("转换后的数组：", Z.astype(np.int32))

# 第2种方法
Y = Z.view(np.int32)
Y[:] = Z
print("转换后的数组：", Y)

原始数组： [97.931145  74.204124  30.164095  21.98578   25.577702   9.66262
 10.632743   2.9900923 39.420517  60.219288 ]
转换后的数组： [97 74 30 21 25  9 10  2 39 60]
转换后的数组： [97 74 30 21 25  9 10  2 39 60]


## 如何读取以下文件 (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [57]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


## numpy数组的枚举（enumerate ）的等价方法是什么？ (★★☆)

In [58]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [59]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## 生成一个通用的二维类高斯分布（Gaussian-like）数组  (★★☆)

类高斯分布也就是2维正态分布，其概率密度函数为$$f(x)=\frac{1}{\sqrt{2 \pi}\sigma}\exp\left(-\frac{(x - \mu)^2}{2 \sigma^2} \right)$$

In [60]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
# 计算距离
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

## 如何在二维数组中随机放置p个元素？ (★★☆)

In [61]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


## 减去矩阵的每一行的平均值  (★★☆)

In [62]:
X = np.random.rand(5, 4)
print("原始矩阵：", X)
Y = X - X.mean(axis=1, keepdims=True)
print("减去矩阵每一行平均值后的矩阵：", Y)

原始矩阵： [[0.24013738 0.50493424 0.97083263 0.04510055]
 [0.90554656 0.74333499 0.41030359 0.40420178]
 [0.11567524 0.83355686 0.42098249 0.49297828]
 [0.1535065  0.75751504 0.40706519 0.81076487]
 [0.24725183 0.22056673 0.74307841 0.09016215]]
减去矩阵每一行平均值后的矩阵： [[-0.20011382  0.06468304  0.53058143 -0.39515065]
 [ 0.28969983  0.12748826 -0.20554314 -0.21164495]
 [-0.35012298  0.36775864 -0.04481572  0.02718006]
 [-0.3787064   0.22530214 -0.12514771  0.27855197]
 [-0.07801295 -0.10469805  0.41781363 -0.23510263]]


## 如何按照第n列的元素大小对数组进行排序？ (★★☆)

In [63]:
Z = np.random.randint(0,10,(3,3))
print("原始数组：", Z)
print("排序后的数组：", Z[ Z[:,1].argsort() ])

原始数组： [[1 7 9]
 [9 9 0]
 [6 6 3]]
排序后的数组： [[6 6 3]
 [1 7 9]
 [9 9 0]]


## 如何判断一个给定的二维数组是否有空列？(★★☆)

In [64]:
Z = np.random.randint(0, 3, (3, 10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 2 1 0 1 2 2 2 2 1]
 [1 0 2 0 0 0 0 0 0 2]
 [1 2 1 1 2 2 0 1 2 2]]
False


## 从数组中找出一个的最接近给定值的值 (★★☆)

In [65]:
Z = np.random.uniform(0,1,10)
print("给定的数组：", Z)
# 给定值
z = 0.5
# 计算绝对值最小的值的索引
m = Z.flat[np.abs(Z - z).argmin()]
print("最接近的值：", m)

给定的数组： [0.590568   0.27218277 0.11618866 0.21123207 0.78879179 0.22150225
 0.27055293 0.8781676  0.84460036 0.78961642]
最接近的值： 0.5905679972820548


## 已知两个维度为(1,3)和(3,1)的数组，如何使用迭代器计算它们的和？(★★☆)

In [66]:
A = np.arange(3).reshape(3,1)
print("A=", A)
B = np.arange(3).reshape(1,3)
print("B=", B)

print(A + B)

A= [[0]
 [1]
 [2]]
B= [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [67]:
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 创建一个具有name属性的数组类(★★☆)

In [68]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


## 已知一个给定的向量，将第二个向量作为第一个向量的索引列表，进行频度计算，即第一个向量的每个元素加1（小心重复的索引）？ (★★★)

In [69]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print("已知的向量：", Z)
print("第2个向量：", I)

np.add.at(Z, I, 1)
print(Z)

已知的向量： [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
第2个向量： [3 9 3 6 2 3 1 8 9 9 7 1 0 8 2 8 8 5 8 5]
[2. 3. 3. 4. 1. 3. 2. 2. 6. 4.]


## 如何根据索引列表(I)将向量(X)的元素累加到数组(F)？ (★★★)

In [70]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I, weights=X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


## 已知类型dtype为ubyte(dtype = ubyte)的(w,h,3)图像，计算不重复颜色的个数（★★★）

In [71]:
w, h = 16, 16
image = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = image[...,0]*256*256 + image[...,1]*256 +image[...,2]
n = len(np.unique(F))
print("不重复的颜色个数：", n)

不重复的颜色个数： 4


## 已知一个四维数组，如何计算最后两个轴的数据之和？(★★★)

In [72]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

[[39 45 60 48]
 [54 49 48 52]
 [59 66 50 60]]


## 已知一维向量D，如何使用相同大小的向量S来计算D的子集的均值，其描述子集索引？(★★★)
Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?

In [73]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.58858194 0.50379731 0.40610167 0.57649067 0.52927629 0.47337903
 0.63288386 0.36719845 0.62654042 0.50281862]


In [74]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.588582
1    0.503797
2    0.406102
3    0.576491
4    0.529276
5    0.473379
6    0.632884
7    0.367198
8    0.626540
9    0.502819
dtype: float64


## 如何计算矩阵点积之后的对角向量？ (★★★)

In [75]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# 运行慢
np.diag(np.dot(A, B))

array([2.1987177 , 0.41551851, 1.36413864, 1.87299678, 0.75223368])

In [76]:
# 运行快
np.sum(A * B.T, axis=1)

array([2.1987177 , 0.41551851, 1.36413864, 1.87299678, 0.75223368])

In [77]:
# 运行更快
np.einsum("ij,ji->i", A, B)

array([2.1987177 , 0.41551851, 1.36413864, 1.87299678, 0.75223368])

## 已知向量[1,2,3,4,5]，如何创建一个新的向量，使得在每个值之间间隔3个连续的零？ (★★★)

In [78]:
Z = np.array([1,2,3,4,5])
nz = 3
# 先创建一个长度为len(Z)+(len(Z)-1)*nz的向量
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
# 将Z向量中的值，间隔nz+1填入Z0矩阵中
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 已知一个维度数组(5,5,3)，如何将它乘以一个维数为(5,5)的数组？ (★★★)

In [79]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))

print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


##  如何交换数组的两行？(★★★)

In [80]:
A = np.arange(25).reshape(5,5)
print("原始数组：\n", A)
A[[0,1]] = A[[1,0]]
print("交换两行之后的数组：\n", A)

原始数组：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
交换两行之后的数组：
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 已知一组描述三角形（具有共享顶点）的10个三元组，找出组成所有三角形的唯一线段（边）的集合  (★★★) 

In [81]:
faces = np.random.randint(0,100,(10,3))
print("已知的三元组：\n", faces)
# 得到所有三角形的边
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
# 其实排序不是必要的，但给出的代码中有排序
# F = np.sort(F,axis=1)
# 进行表示、去重
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print("得到的边集合：\n", G)

已知的三元组：
 [[19  1 94]
 [87 49 77]
 [ 4 40 30]
 [38 52  5]
 [40 96 99]
 [49 29 90]
 [48 10 69]
 [73 31 66]
 [67 23 35]
 [38 99  2]]
得到的边集合：
 [( 1, 94) ( 2, 38) ( 4, 40) ( 5, 38) (10, 69) (19,  1) (23, 35) (29, 90)
 (30,  4) (31, 66) (35, 67) (38, 52) (38, 99) (40, 30) (40, 96) (48, 10)
 (49, 29) (49, 77) (52,  5) (66, 73) (67, 23) (69, 48) (73, 31) (77, 87)
 (87, 49) (90, 49) (94, 19) (96, 99) (99,  2) (99, 40)]


## 已知一个bincount的数组C，如何生成一个数组A，使得 np.bincount(A) == C? (★★★)

In [82]:
C = np.bincount([1,1,2,3,4,4,6])
print("已知数组C：", C)
A = np.repeat(np.arange(len(C)), C)
print("生成的数组A：", A)
print("验证结果：", np.bincount(A) == C)

已知数组C： [0 2 1 1 2 0 1]
生成的数组A： [1 1 2 3 4 4 6]
验证结果： [ True  True  True  True  True  True  True]


## 如何使用数组上的滑动窗口计算平均值？(★★★)

In [83]:
def moving_average(a, n=3) :
    # 计算累加和
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## 已知一维数组Z，创建一个二维数组，其第一行为(Z[0],Z[1],Z[2])，后面每行移动1 个元素 (最后一行应该是Z[-3],Z[-2],Z[-1]) (★★★)

In [84]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


##  如何对布尔数组取反，或改变浮点数组的符号？ (★★★)

In [85]:
# 对布尔数组取反
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print(Z)

# 对浮点数组取反
Z = np.random.uniform(-1.0,1.0,100)
print(np.negative(Z, out=Z))

[0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1
 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 0 1 0 0 0 1
 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1]
[ 0.83071501  0.02228517  0.03866726  0.09190128  0.80184497  0.945868
  0.72810236 -0.40521222 -0.74849258 -0.90239468 -0.36059033  0.54202506
  0.30953333  0.78265383  0.99725761 -0.70126231 -0.90381373 -0.24902524
  0.68719225  0.34800352  0.78446983  0.34372014  0.11504463  0.49717187
 -0.40442564  0.40640194 -0.73431816 -0.23199119  0.59723708 -0.18585287
  0.79252362  0.00462576 -0.00767783 -0.85437701  0.43415081  0.78977122
 -0.40998959  0.41409361 -0.88117124 -0.16403014 -0.38582876  0.97271422
  0.97426102  0.65519626 -0.17945488 -0.93598769 -0.70886736  0.21228726
  0.72030803  0.12977045 -0.88183195  0.34554051  0.82777409 -0.28165398
  0.66896579  0.41280858 -0.57824251  0.60060719 -0.54708716 -0.7447967
  0.89297343  0.44841302 -0.83999681  0.13737311 -0.07498886  0.36047

## 已知2组用二元组(P0,P1)描述线(2d)的数组和点p，如何计算从p到每条线的距离i (P0[i],P1[i]) (★★★)

In [86]:
def distance(P0, P1, p):
    # 计算两端之间线段的长度
    T = P1 - P0
    L = (T**2).sum(axis=1)
    # 求出交叉点的偏移距离
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    # 计算交叉点与点p的距离
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
print("P0：\n", P0)
print("P1：\n", P1)
p  = np.random.uniform(-10,10,( 1,2))
print("p：\n", p)
print("点p到各线段的长度：\n", distance(P0, P1, p))

P0：
 [[-7.32416185 -8.12250974]
 [-3.83287581  3.63074306]
 [ 5.4800023   6.10831991]
 [ 9.71853315  7.04425319]
 [ 0.04802915  1.1116882 ]
 [-9.65413379 -6.01809181]
 [-0.02542329 -7.17171651]
 [ 2.04456038 -4.77836477]
 [-7.00752407  7.68416021]
 [-1.41548875  9.53262912]]
P1：
 [[ 4.91793007  2.81814445]
 [ 4.54349647  5.23735067]
 [ 1.75508962  3.0943244 ]
 [ 3.52596161  3.10645675]
 [-7.60828476  3.37387575]
 [ 4.34380994  8.22127316]
 [ 1.18395243  7.2474722 ]
 [-2.49779062 -9.8555351 ]
 [ 8.15111291 -5.88476454]
 [-4.81816724 -1.291814  ]]
p：
 [[-9.70466974  9.42305731]]
点p到各线段的长度：
 [14.66875433  6.79468485 12.12830874 12.42965525  5.20722722 10.86083361
 11.03235805 18.22533252  0.50323383  7.87481928]


## 已知2组用二元组(P0,P1)描述线(2d)的数组和一个点P的数组，如何计算每个点j (P[j])到每个线段的距离i (P0[i],P1[i])?(★★★)

In [87]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
print("P0：\n", P0)
print("P1：\n", P1)
p = np.random.uniform(-10, 10, (10,2))
print("p：\n", p)
print("点p到各线段的长度：\n", np.array([distance(P0,P1,p_i) for p_i in p]))

P0：
 [[ 1.41587475  5.41818626]
 [ 2.07680137  7.048377  ]
 [-9.75223309 -4.51870169]
 [-9.7377465  -1.60540789]
 [ 5.30292092  5.798051  ]
 [ 5.37715177 -3.00433811]
 [ 2.81297407  8.81699011]
 [ 4.01619502  8.41885811]
 [-9.20321133 -0.08828808]
 [ 1.4447847   6.19106952]]
P1：
 [[ 5.79089779 -7.52377095]
 [-4.36783648 -8.58537803]
 [ 6.79472154 -4.62964212]
 [-8.6314212  -3.62006533]
 [-3.84158646  7.46769795]
 [ 4.43410888 -9.49896638]
 [-9.20987808  3.98569004]
 [-1.14355837  7.99616751]
 [ 0.05819731  5.50054887]
 [ 5.63459186  8.9030579 ]]
p：
 [[-7.16556031  9.68389055]
 [ 5.74552548 -1.05492346]
 [ 2.62910551 -6.03787137]
 [ 9.18802173  5.39190949]
 [-8.76892813 -8.3144235 ]
 [ 5.32117189  5.88770306]
 [ 8.41332572  1.1792757 ]
 [-3.71575201  2.32958835]
 [-1.38283226 -6.07039505]
 [-6.7863443  -3.74934541]]
点p到各线段的长度：
 [[ 6.76341411  9.5492534  14.21961521  7.68858629  1.58311397 14.23579616
   4.52502584  2.17376776  7.31400582  7.61088922]
 [ 2.02863973  6.48012161  3.5676040

## 已知一个任意数组，编写一个函数，以给定元素为中心，获得具有固定维度的子数组（多余部分用fill的值填充）(★★★)

In [88]:
# 已知的数组Z
Z = np.random.randint(0,10,(10,10))
# 固定维度
shape = (5,5)
# 填充值
fill  = 0
# 中心点
position = (1,1)

# 进行初始化
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

# 初始化要从Z中获取的子矩阵大小(Z_start, Z_stop)，赋值到R矩阵里面的位置(R_start, R_stop)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

# 修正两个位置
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
print("赋值R矩阵的位置：", (R_start, R_stop))
print("截取Z矩阵的位置：", (Z_start, Z_stop))

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
print(r, z)
R[tuple(r)] = Z[tuple(z)]
print("已知的数组：\n", Z)
print("以", position, "为中心，维度为", shape, "的子矩阵：\n", R)

赋值R矩阵的位置： ([1, 1], [5, 5])
截取Z矩阵的位置： ([0, 0], [4, 4])
[slice(1, 5, None), slice(1, 5, None)] [slice(0, 4, None), slice(0, 4, None)]
已知的数组：
 [[3 5 5 4 6 3 9 3 2 3]
 [4 3 1 5 1 2 6 7 4 8]
 [9 0 8 5 3 0 5 4 3 2]
 [4 6 4 0 2 4 0 4 4 7]
 [5 2 1 2 3 5 5 6 2 1]
 [8 1 2 0 9 5 6 1 7 1]
 [5 8 6 2 2 3 3 1 2 9]
 [8 6 3 8 9 7 3 3 6 7]
 [3 3 2 2 6 8 3 7 5 0]
 [4 0 6 2 3 7 9 4 7 2]]
以 (1, 1) 为中心，维度为 (5, 5) 的子矩阵：
 [[0 0 0 0 0]
 [0 3 5 5 4]
 [0 4 3 1 5]
 [0 9 0 8 5]
 [0 4 6 4 0]]


## 已知一个数组 Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]，如何生成一个数组 R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]？ (★★★)

In [89]:
Z = np.arange(1, 15, dtype=np.int32)
R = np.lib.stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## 计算矩阵的秩 (★★★)

In [90]:
Z = np.random.uniform(0,1,(10,10))
# 采用SVD分解，得到特征向量
U, S, V = np.linalg.svd(Z) 
# 计算非零元素的个数
rank = np.sum(S > 1e-10)
print(rank)

10


In [91]:
print(np.linalg.matrix_rank(Z))

10


## 如何在数组中找到最常见（频度最高）的值？ (★★★)

In [92]:
Z = np.random.randint(0,10,50)
print("已知数组Z：\n", Z)
# 采用np.bincount(Z)计算频度，取最高的值
print("计算频度：\n", np.bincount(Z))
print("频度最高的值：", np.bincount(Z).argmax())

已知数组Z：
 [5 3 3 2 1 1 7 4 5 0 1 5 3 1 5 8 5 3 1 2 8 5 9 1 2 7 3 7 9 5 6 0 6 2 1 1 5
 9 5 7 3 1 4 4 4 1 9 5 8 1]
计算频度：
 [ 2 11  4  6  4 10  2  4  3  4]
频度最高的值： 1


## 从10x10随机矩阵中得到所有连续的3x3子矩阵 (★★★)

In [93]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 3 2]
   [3 0 3]
   [0 1 0]]

  [[3 2 1]
   [0 3 4]
   [1 0 4]]

  [[2 1 0]
   [3 4 1]
   [0 4 0]]

  [[1 0 0]
   [4 1 0]
   [4 0 0]]

  [[0 0 3]
   [1 0 2]
   [0 0 1]]

  [[0 3 3]
   [0 2 3]
   [0 1 3]]

  [[3 3 1]
   [2 3 3]
   [1 3 3]]

  [[3 1 0]
   [3 3 2]
   [3 3 3]]]


 [[[3 0 3]
   [0 1 0]
   [0 1 1]]

  [[0 3 4]
   [1 0 4]
   [1 1 3]]

  [[3 4 1]
   [0 4 0]
   [1 3 3]]

  [[4 1 0]
   [4 0 0]
   [3 3 4]]

  [[1 0 2]
   [0 0 1]
   [3 4 0]]

  [[0 2 3]
   [0 1 3]
   [4 0 3]]

  [[2 3 3]
   [1 3 3]
   [0 3 2]]

  [[3 3 2]
   [3 3 3]
   [3 2 2]]]


 [[[0 1 0]
   [0 1 1]
   [0 0 3]]

  [[1 0 4]
   [1 1 3]
   [0 3 4]]

  [[0 4 0]
   [1 3 3]
   [3 4 3]]

  [[4 0 0]
   [3 3 4]
   [4 3 0]]

  [[0 0 1]
   [3 4 0]
   [3 0 0]]

  [[0 1 3]
   [4 0 3]
   [0 0 0]]

  [[1 3 3]
   [0 3 2]
   [0 0 4]]

  [[3 3 3]
   [3 2 2]
   [0 4 4]]]


 [[[0 1 1]
   [0 0 3]
   [0 1 3]]

  [[1 1 3]
   [0 3 4]
   [1 3 2]]

  [[1 3 3]
   [3 4 3]
   [3 2 2]]

  [[3 3 4]
   [4 3 0]
   [2 2 0]]

  [[3 4 0]
   

##  创建一个二维数组子类，使得Z[i,j] == Z[j,i] （即对角矩阵）(★★★)

In [94]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

Z = np.random.randint(0,10,(5,5))
print("已知二维矩阵：\n", Z)
S = symetric(Z)
print("生成矩阵：\n", S)

已知二维矩阵：
 [[2 3 2 7 3]
 [1 7 8 4 5]
 [1 2 2 6 6]
 [8 8 6 7 1]
 [1 4 8 4 8]]
生成矩阵：
 [[ 2  4  3 15  4]
 [ 4  7 10 12  9]
 [ 3 10  2 12 14]
 [15 12 12  7  5]
 [ 4  9 14  5  8]]


## 已知一组维度为(n,n)的p矩阵和一组维度为(n,1)的p向量，如何通过一次计算得到矩阵乘积之后的各矩阵和？（结果矩阵的维度为(n,1)）(★★★)

In [95]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


## 已知一个16x16的矩阵，如何获得子矩阵的和？（子矩阵大小为4x4） (★★★)

In [96]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


## 如何使用numpy数组实现游戏生命（the Game of Life）？(★★★)

The Game Of Life（生命游戏，又称为细胞自动机）几乎是所有数据结构与算法导论教程前言的一个很经典的程序了。这是一个零玩家游戏，发生在一个平面网格里。每个格子的细胞都有死亡和存活两种状态，在代与代之间有两种状态，如果每一个细胞周围少于或等于1个细胞或多于4个细胞时，他会在下一代死亡；如果一个格子周围恰好有3个细胞，他将会重新活过来。

In [97]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(10,10))
for i in range(100): 
    Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


## 如何获取数组的n个最大值 (★★★)

In [98]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# 运行慢
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [99]:
# 运行快
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9998 9999 9996 9995]


## 给定多个不同维度的向量，构建笛卡尔积（即从每个向量中取出一个元素组成一个向量）(★★★)

In [100]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    # 得到生成笛卡尔积的每个数组的index数组
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


## 如何从常规数组创建记录数组？ (★★★)
How to create a record array from a regular array?

In [101]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


## 已知一个维度很大的向量Z，使用3种不同的方法计算Z的3次幂(★★★)

In [102]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.34 s ± 47.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
380 ms ± 12.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
231 ms ± 4.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 已知维度为 (8,3) 和 (2,2) 的两个矩阵A和B，如何查找在B矩阵中的各行元素出现在A矩阵中，且不考虑B中元素的顺序？(★★★)

In [103]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print("A矩阵：\n", A)
print("B矩阵：\n", B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print("在A矩阵中满足条件的行：\n", rows)

A矩阵：
 [[4 0 0]
 [0 4 2]
 [4 0 2]
 [2 4 3]
 [2 4 1]
 [1 2 1]
 [4 3 4]
 [0 0 4]]
B矩阵：
 [[4 3]
 [2 0]]
在A矩阵中满足条件的行：
 [0 1 2 3 4 7]


## 已知一个10x3的矩阵，获取具有不同值的行 (e.g. [2,2,3]) (★★★)

In [104]:
Z = np.random.randint(0,2,(10,3))
print("矩阵Z(10x3)：\n", Z)
# 可用于处理所有数据类型的数组（包括字符串数组和记录数组）
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print("不同值的行：\n", U)

矩阵Z(10x3)：
 [[1 0 1]
 [0 0 0]
 [0 0 1]
 [1 1 0]
 [0 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 0]]
不同值的行：
 [[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]]


In [105]:
# 只适用于数值数组，适用于Z中任意数量的列
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print("不同值的行：\n", U)

不同值的行：
 [[1 0 1]
 [0 0 1]
 [1 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]]


## 将int的向量转换为矩阵二进制表示  (★★★)

In [106]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [107]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## 给定一个二维数组，如何获得唯一的行？(★★★)

In [108]:
Z = np.random.randint(0,2,(6,3))
print("数组Z：\n", Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print("满足条件的行：\n", uZ)

数组Z：
 [[1 0 1]
 [0 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 0]
 [0 1 0]]
满足条件的行：
 [[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [109]:
uZ = np.unique(Z, axis=0)
print("满足条件的行：\n", uZ)

满足条件的行：
 [[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


## 已知2个向量A和B，写出einsum等效的inner，outer，sum和mul函数 (★★★)

In [110]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)
print("A向量：\n", A)
print("B向量：\n", B)

# np.sum(A)
print("np.sum(A)：\n", np.einsum('i->', A))
# A * B
print("A * B：\n", np.einsum('i,i->i', A, B)) 
# np.inner(A, B)
print("np.inner(A, B)：\n", np.einsum('i,i', A, B))
# np.outer(A, B)
print("np.outer(A, B): \n", np.einsum('i,j->ij', A, B))    

A向量：
 [0.17852193 0.96643717 0.97208705 0.89154435 0.93511994]
B向量：
 [0.23600998 0.93600263 0.924735   0.73101501 0.30909365]
np.sum(A)：
 3.943710442037092
A * B：
 [0.04213296 0.90458773 0.89892292 0.6517323  0.28903963]
np.inner(A, B)：
 2.786415539536347
np.outer(A, B): 
 [[0.04213296 0.167097   0.16508548 0.13050221 0.05517999]
 [0.22808881 0.90458773 0.89369828 0.70648007 0.29871959]
 [0.22942224 0.90987603 0.89892292 0.71061023 0.30046593]
 [0.21041336 0.83448785 0.82444227 0.6517323  0.27557069]
 [0.22069764 0.87527472 0.86473814 0.68358671 0.28903963]]


## 已知两个矢量(X,Y)描述的路径，如何使用等距样本对其进行采样？(★★★)
Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?

In [111]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

# segment lengths
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
# integrate path
r[1:] = np.cumsum(dr)               
# regular spaced path
r_int = np.linspace(0, r.max(), 200) 
# integrate path
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

## 给定一个整数n和一个2维数组X，从X中选择具有n度的多项分布的行，即仅包含整数并且总和为n的行 (★★★)

In [112]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


## 计算95％置信区间一维矩阵X的平均值（即重新采样具有替换N次的阵列的元素，计算每个样本的平均值，然后计算均值上的百分位数）(★★★)
Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 

In [113]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.00774102  0.41960099]
